# Generated by Django 2.2.7 on 2019-11-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='descri',
            field=models.TextField(default='holamundo'),
            preserve_default=False,
        ),
    ]
